Updated to newer version of the fork origin.

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,17 +1,14 @@
-#!/bin/sh
+#!/bin/bash
 # usage: bin/compile <build-dir> <cache-dir>
 
-set -e
-
-echo "-----> BUILD: $1"
-echo "-----> CACHE: $2"
+set -eo pipefail
 
 mkdir -p "$1" "$2"
 build=$(cd "$1/" && pwd)
 cache=$(cd "$2/" && pwd)
-ver=1.0.2
-file=go$ver.linux-amd64.tar.gz
-url=http://go.googlecode.com/files/$file
+ver=${GOVERSION:-1.0.3}
+file=${GOFILE:-go$ver.$(uname|tr A-Z a-z)-amd64.tar.gz}
+url=${GOURL:-http://go.googlecode.com/files/$file}
 buildpack=$(dirname $(dirname $0))
 
 # Python
@@ -26,62 +23,50 @@ virtualenv() {
 
 if ! test -f $build/.godir
 then
-    echo >&2 '-----> ERROR: Please create .godir'
-    echo >&2 '-----> See https://gist.github.com/299535bbf56bf3016cba for instructions'
+    echo >&2 " !     A .godir is required."
+    echo >&2 " !     See https://gist.github.com/299535bbf56bf3016cba for instructions."
     exit 1
 fi
 
 if test -e $build/bin && ! test -d $build/bin
 then
-    echo >&2 '-----> ERROR: File bin exists and is not a directory.'
+    echo >&2 " !     File bin exists and is not a directory."
     exit 1
 fi
 
-echo "-----> Using Go $ver"
-
-(
-    set -e
-
-    # Already cached?
-    test -d $cache/go-$ver/go && exit
-
+if test -d $cache/go-$ver/go
+then
+    echo "-----> Using Go $ver"
+else
     rm -rf $cache/* # be sure not to build up cruft
     mkdir -p $cache/go-$ver
     cd $cache/go-$ver
-    echo "-----> Fetching Go $ver"
+    echo -n "-----> Installing Go $ver..."
     curl -sO $url
     tar zxf $file
     rm -f $file
-)
+    echo " done"
+fi
 
 GOROOT=$cache/go-$ver/go export GOROOT
-#GOPATH=$build/.heroku/g export GOPATH
-#GOPATH=/app/tmp/repo.git export GOPATH
-GOPATH=/app/tmp/repo.git/src/rtrt export GOPATH
-PATH=$GOROOT/bin:$build/bin:/app/bin:$PATH export PATH
+GOPATH=$build/.heroku/g export GOPATH
+PATH=$GOROOT/bin:$PATH
 
-echo "GOPATH: $GOPATH"
+if ! (which hg > /dev/null && which bzr > /dev/null)
+then
+    echo -n "       Installing Virtualenv..."
+    virtualenv --python $python --distribute --never-download --prompt='(venv) ' $venv > /dev/null 2>&1
+    . $venv/bin/activate > /dev/null 2>&1
+    echo " done"
 
-echo "-----> Checking for Mercurial and Bazaar"
-(
-    set -e
-    which hg && which bzr && which git exit
-    echo "Installing Mercurial and Bazaar"
+    echo -n "       Installing Mercurial..."
+    pip install --use-mirrors mercurial > /dev/null 2>&1
+    echo " done"
 
-    virtualenv --python $python --distribute --never-download --prompt='(venv) ' $venv
-    if [ "$?" -ne 0 ]; then
-        echo "Warning: Python environment corrupted. Rebuilding"
-        rm -rf $venv/* || true
-        virtualenv --python $python --distribute --never-download --prompt='(venv) ' $venv
-    fi
-    . $venv/bin/activate
-
-    pip install --use-mirrors mercurial
-    pip install --use-mirrors bzr
-    pip install --use-mirrors git
-) 2>&1 | sed -u 's/^/       /'
-
-#git --version
+    echo -n "       Installing Bazaar..."
+    pip install --use-mirrors bzr > /dev/null 2>&1
+    echo " done"
+fi
 
 name=$(cat $build/.godir)
 p=$GOPATH/src/$name
@@ -108,18 +93,14 @@ git clone git://github.com/bmizerany/pq $GOPATH/src/github.com/bmizerany/pq
 echo "*** Cloned bmizerany! ***"
 go get github.com/bmizerany/pq
 
-echo "-----> Running go get (app)"
-#export GOPATH=`pwd` # Debug
-#echo $GOPATH
-ls
-echo ''
-echo "`pwd`/src:"
-ls src
+echo "-----> Running: go get ./..."
+cd $p
+#go get ./...
 go install rtrt/frontend
 
-# Finally, move compiled binary to $build/bin
-# Heroku will move the contents of this dir to /app/bin afterwards.
 mkdir -p $build/bin
 mv $GOPATH/bin/* $build/bin
+rm -rf $build/.heroku
 
-GIT_SSL_NO_VERIFY=true rm -rf $build/.heroku # Does this need to be deleted?
+mkdir -p $build/.profile.d
+echo 'export PATH=$PATH:$HOME/bin' > $build/.profile.d/go.sh
